// apps/wealth-react/app/components/add-ticker.tsx
import { useState } from "react";

interface AddTickerProps {
    onAdd: (symbol: string) => void;
}

export function AddTicker({ onAdd }: AddTickerProps) {
    const [value, setValue] = useState("");

    function handleSubmit(e: React.FormEvent) {
        e.preventDefault();
        const trimmed = value.trim().toUpperCase();
        if (!trimmed) return;
        onAdd(trimmed);
        setValue("");
    }

    return (
        <form
            className="add-form"
            onSubmit={handleSubmit}
        >
            <input
                type="text"
                value={value}
                onChange={(e) => setValue(e.target.value)}
                placeholder="Enter ticker symbol"
            />
            <button type="submit">Add</button>
        </form>
    );
}

// apps/wealth-solid/src/components/add-ticker.tsx
import { type Component, createSignal } from "solid-js";

interface AddTickerProps {
    onAdd: (symbol: string) => void;
}

const AddTicker: Component<AddTickerProps> = (props) => {
    const [symbol, setSymbol] = createSignal("");

    const handleSubmit = (e: SubmitEvent) => {
        e.preventDefault();
        const value = symbol().trim().toUpperCase();
        if (value) {
            props.onAdd(value);
            setSymbol("");
        }
    };

    return (
        <form
            class="add-ticker"
            onSubmit={handleSubmit}
        >
            <input
                type="text"
                value={symbol()}
                onInput={(e) => setSymbol(e.currentTarget.value)}
                placeholder="Enter ticker symbol (e.g. AAPL)"
            />
            <button
                type="submit"
                disabled={!symbol().trim()}
            >
                Add
            </button>
        </form>
    );
};

export default AddTicker;
