// apps/wealth-solid/src/components/ticker-list.tsx
import type { Quote, Ticker } from "@m0n0lab/wealth-tracker-core";
import { type Component, For, Show } from "solid-js";
import TickerRow from "./ticker-row";

interface TickerListProps {
    tickers: Ticker[];
    quotes: Map<string, Quote>;
    onRemove: (symbol: string) => void;
}

const TickerList: Component<TickerListProps> = (props) => {
    return (
        <Show
            when={props.tickers.length > 0}
            fallback={
                <div class="empty-state">
                    No tickers added yet. Add a symbol above to get started.
                </div>
            }
        >
            <div class="ticker-list">
                <For each={props.tickers}>
                    {(ticker) => (
                        <TickerRow
                            ticker={ticker}
                            quote={props.quotes.get(ticker.symbol)}
                            onRemove={props.onRemove}
                        />
                    )}
                </For>
            </div>
        </Show>
    );
};

export default TickerList;

// apps/wealth-react/app/components/ticker-list.tsx
import { TickerRow } from "./ticker-row";
import type { Quote, Ticker } from "@m0n0lab/wealth-tracker-core";

interface TickerListProps {
    tickers: Ticker[];
    quotes: Map<string, Quote>;
    onRemove: (symbol: string) => void;
}

export function TickerList({ tickers, quotes, onRemove }: TickerListProps) {
    if (tickers.length === 0) {
        return <div className="empty-state">No tickers added. Use the form above to add one.</div>;
    }

    const sorted = [...tickers].sort((a, b) => a.symbol.localeCompare(b.symbol));

    return (
        <div className="ticker-list">
            {sorted.map((ticker) => (
                <TickerRow
                    key={ticker.symbol}
                    ticker={ticker}
                    quote={quotes.get(ticker.symbol)}
                    onRemove={onRemove}
                />
            ))}
        </div>
    );
}
